version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
  post_build:
    commands:
      - docker run -p $port_container:$port_external $IMAGE_REPO_NAME:$IMAGE_TAG

      
